[package]
name = "bridge-vault"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.5.7"
solana-program = "3.0.0"
spl-token = "9.0.0"
thiserror = "2.0.17"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
